import Head from 'next/head';
import {BNBChain} from 'components/protocols';
import Home from 'components/shared/Home';

export default function Index() {
  return (
    <>
      <Head>
        <title>BNB Chain Learn Web3 Stack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </>
  );
}
